"""Generate responsive case previews; keep originals for full-size viewing.

Run with Python 3 and Pillow: python scripts/optimize-case-images.py
"""
from io import BytesIO
import json
import re
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
sources = set(re.findall(r'"src": "(/assets/cases/[^\"]+)"', (ROOT / 'src/data/case-content.ts').read_text()))
sources.update('/assets/' + name for name in ['copter-concepts.png', 'primekraft-concepts.png', '4sales-concepts.png'])
output = ROOT / 'public/assets/responsive'
output.mkdir(exist_ok=True)
def save_webp(image, destination, quality):
    encoded = BytesIO()
    image.save(encoded, 'WEBP', quality=quality, method=6)
    data = encoded.getvalue()
    # Validate before replacing the artifact; interrupted runs cannot leave empty images.
    Image.open(BytesIO(data)).load()
    temporary = destination.with_suffix('.tmp')
    temporary.write_bytes(data)
    temporary.replace(destination)

manifest = {}
totals = {'original_bytes': 0, 'mobile_bytes': 0, 'desktop_bytes': 0, 'images': len(sources)}
for source in sorted(sources):
    path = ROOT / 'public' / source.lstrip('/')
    image = Image.open(path).convert('RGB')
    candidates = []
    for width in [640, 1160, 1600]:
        if width >= image.width:
            continue
        name = f'{path.stem}-{width}.webp'
        resized = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
        save_webp(resized, output / name, 92)
        candidates.append({'src': f'/assets/responsive/{name}', 'width': width})
    if path.suffix == '.png':
        name = f'{path.stem}-{image.width}.webp'
        save_webp(image, output / name, 95)
        candidates.append({'src': f'/assets/responsive/{name}', 'width': image.width})
    else:
        candidates.append({'src': source, 'width': image.width})
    fallback = next(item['src'] for item in candidates if item['width'] >= 1160)
    manifest[source] = {'fallback': fallback, 'candidates': candidates}
    totals['original_bytes'] += path.stat().st_size
    totals['mobile_bytes'] += (ROOT / 'public' / candidates[0]['src'].lstrip('/')).stat().st_size
    totals['desktop_bytes'] += (ROOT / 'public' / fallback.lstrip('/')).stat().st_size
(ROOT / 'src/data/responsive-images.ts').write_text('// Generated by scripts/optimize-case-images.py; original assets are preserved.\nexport const responsiveImages: Record<string, { fallback: string; candidates: { src: string; width: number }[] }> = ' + json.dumps(manifest, ensure_ascii=False, indent=2) + ';\n')
print(json.dumps(totals))
